### ISSUE TITLE
error: option --single-version-externally-managed not recognized

### ISSUE THREAD

**Issue by Ergodic-Commiter** [multiplay/mysql-connector-python#6]
I am following a tutorial for using Django, and I came accross the above error on installing `mysql-connector-python`.  I have looked for several posts regarding this issue -mostly in stackoverflow-, but I still haven't managed to fix my connection with MySQL.  

My setup is:  
- virtual environment with Python 3.4, and Django 1.8. 
- mysql  Ver 14.14 Distrib 5.6.25.
- trying mysql-connector-python==2.0.4.

What I've tried to do to fix this is:
- `pip install mysql-python` which apparently isn't supported on Python 3. 
- `pip install --allow-external mysql-connector-python mysql-connector-python` gets installed properly, but throws an error after `python manage.py runserver`; 
  
  ```
  ImproperlyConfigured: 'mysql.connector.django' isn't an available database backend.
  Try using 'django.db.backends.XXX', where XXX is one of:
  'base', 'mysql', 'oracle', 'postgresql_psycopg2', 'sqlite3'
  Error was: cannot import name 'BaseDatabaseFeatures'
  ```
  
  Thus, changing to `django.db.backends.mysql` throws the error 
  
  ```
  ImproperlyConfigured: Error loading MySQLdb module: No module named 'MySQLdb'
  ```
- `pip install git+https://github.com/multiplay/mysql-connector-python` and changing the configuration to `mysql.connector.django` throws the error mentioned above.  

Please let me know if I can give you more info.  Thank you kindly. 
This is the link to [pip.log](http://pastebin.com/EcvCdhd1)

**Comment by leepa** [comment]
`pip install -e` if you are installing from Git.

Either way we do not make mysql-connector-python. Proper support is available from the guys at Oracle. We merely fork it as they don't merge fixes which have bug reports against for over a year now.

**Comment by Ergodic-Commiter** [comment]
Thank you, I actually went around using this connector, since `mysqlclient` package made the proper connection finally.  
Regards from Mexico.
