### ISSUE TITLE
Update PYPI

### ISSUE THREAD

**Issue by vcajes** [multiplay/mysql-connector-python#7]
There is a new version of the mysql-connector-python that you have uploaded to pypi at https://pypi.python.org/pypi/mysql-connector-python/2.0.4

Many people are now using Django 1.8, and this connector 2.0.4 does not work with Django 1.8

But the version 2.1.3 works fine with Django. Link to version 2.1.3 http://dev.mysql.com/downloads/connector/python/

Could you please update your pypi repository to this latest version please?

Thank you so much for this!

**Comment by leepa** [comment]
We do not manage the pypi versioning. This is a fork.
